import { MigrationInterface, QueryRunner } from "typeorm";

export class AlterPermissions1747265304369 implements MigrationInterface {
    name = 'AlterPermissions1747265304369'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "fk_user_course"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP CONSTRAINT "FK_4133c0b3d932b97c4edd337f073"`);
        await queryRunner.query(`ALTER TABLE "dutyRequestPosition" DROP CONSTRAINT "FK_143a4eba4f39ad407626f68d71a"`);
        await queryRunner.query(`ALTER TABLE "duty" DROP CONSTRAINT "FK_81904955122e0a5759c6f9d79ab"`);
        await queryRunner.query(`ALTER TABLE "duty" DROP CONSTRAINT "FK_f868506683edeb8fa7d4fb00482"`);
        await queryRunner.query(`ALTER TABLE "duty" DROP CONSTRAINT "FK_19582ae87fdb3eab7a97680122f"`);
        await queryRunner.query(`ALTER TABLE "duty" DROP CONSTRAINT "FK_f5b4ceb89f9a290d99b6f1a4a3d"`);
        await queryRunner.query(`ALTER TABLE "duty" DROP CONSTRAINT "FK_0b047dd0eba2c67fa5bc88c6a1e"`);
        await queryRunner.query(`ALTER TABLE "duty" DROP CONSTRAINT "FK_9066788443fa413b6b247125249"`);
        await queryRunner.query(`ALTER TABLE "duty" DROP CONSTRAINT "FK_6a066490fc535fc3aaf3118a29a"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP CONSTRAINT "FK_713225778ff4cffe1f55d535b7d"`);
        await queryRunner.query(`ALTER TABLE "checklistFilled" DROP CONSTRAINT "FK_12e865c85e6303467ce0962e0a4"`);
        await queryRunner.query(`ALTER TABLE "checklistQuestion" DROP CONSTRAINT "FK_2cf93290d25cc20f5e1ca3fe248"`);
        await queryRunner.query(`ALTER TABLE "checklistQuestionItem" DROP CONSTRAINT "FK_0bdcd18d14d0dbe1b546e0688c6"`);
        await queryRunner.query(`ALTER TABLE "checklistQuestionOption" DROP CONSTRAINT "FK_b5773438b5a3723dcbcc3f7fea7"`);
        await queryRunner.query(`ALTER TABLE "checklistFilledAnswer" DROP CONSTRAINT "FK_3b88b91acc96fa110dbca8bdf3b"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP CONSTRAINT "FK_49d69c43dcc611ab038cabcb132"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP CONSTRAINT "FK_04dc7ec62b5c70614ca5055d316"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP CONSTRAINT "FK_00927e963a8a4c3b0f9f06c1aa0"`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "createdAt" SET DEFAULT '"2025-05-14T23:28:25.954Z"'`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "permission"`);
        await queryRunner.query(`DROP TYPE "public"."user_permission"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "permission" character varying DEFAULT 'TRAINEE'`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."user_status"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "status" character varying DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "deletedBy"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "deletedBy" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "createdAt" SET DEFAULT '"2025-05-14T23:28:25.954Z"'`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "courseId"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "courseId" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_660cced3eb3232d317a712dd001" UNIQUE ("courseId")`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "approvedBy"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "approvedBy" character varying`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "date" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "shift"`);
        await queryRunner.query(`DROP TYPE "public"."duty_shift"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "shift" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "startAt"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "startAt" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "endAt"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "endAt" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-05-14T23:28:25.961Z"'`);
        await queryRunner.query(`ALTER TABLE "dutyRequestPosition" DROP COLUMN "dutyRequestId"`);
        await queryRunner.query(`ALTER TABLE "dutyRequestPosition" ADD "dutyRequestId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequestPosition" DROP COLUMN "position"`);
        await queryRunner.query(`DROP TYPE "public"."dutyRequestPosition_position_enum"`);
        await queryRunner.query(`ALTER TABLE "dutyRequestPosition" ADD "position" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "date" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "shift"`);
        await queryRunner.query(`DROP TYPE "public"."duty_shift"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "shift" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "leaderId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "leaderId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "driverId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "driverId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "firstRescuerId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "firstRescuerId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "secondRescuerId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "secondRescuerId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "radioOperatorId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "radioOperatorId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "assistantRadioOperatorId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "assistantRadioOperatorId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "traineeId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "traineeId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "isAvailable"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "isAvailable" character varying NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "duty" ALTER COLUMN "note" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" ALTER COLUMN "note" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT '"2025-05-14T23:28:25.972Z"'`);
        await queryRunner.query(`ALTER TABLE "vehicle" ALTER COLUMN "isAvailable" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "vehicle" ALTER COLUMN "createdAt" SET DEFAULT '"2025-05-14T23:28:25.978Z"'`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP CONSTRAINT "FK_78aed4cb170c4e9c7ba680c46ba"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP CONSTRAINT "FK_800582b77a039f930307845a062"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP CONSTRAINT "FK_8d237bd7fc350432caf1f1739bb"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP COLUMN "vehicleId"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD "vehicleId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD CONSTRAINT "UQ_78aed4cb170c4e9c7ba680c46ba" UNIQUE ("vehicleId")`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP COLUMN "driverId"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD "driverId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD CONSTRAINT "UQ_800582b77a039f930307845a062" UNIQUE ("driverId")`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD "date" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP COLUMN "startAt"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD "startAt" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP COLUMN "endAt"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD "endAt" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP COLUMN "createdByUserId"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD "createdByUserId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD CONSTRAINT "UQ_8d237bd7fc350432caf1f1739bb" UNIQUE ("createdByUserId")`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ALTER COLUMN "createdAt" SET DEFAULT '"2025-05-14T23:28:25.987Z"'`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP CONSTRAINT "FK_f967b4eafc0b1af447f956cabf0"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP CONSTRAINT "FK_c7a2d2e78610ad29525679eaf1b"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "dutyId"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "dutyId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD CONSTRAINT "UQ_1b9b613872a6965166623632721" UNIQUE ("dutyId")`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "date" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "time"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "time" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "vehicleId"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "vehicleId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD CONSTRAINT "UQ_f967b4eafc0b1af447f956cabf0" UNIQUE ("vehicleId")`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "victimGender"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "victimGender" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "incidentContinuation"`);
        await queryRunner.query(`DROP TYPE "public"."incident_continuation"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "incidentContinuation" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "checklistFilledId"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "checklistFilledId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "createdByUserId"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "createdByUserId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD CONSTRAINT "UQ_c7a2d2e78610ad29525679eaf1b" UNIQUE ("createdByUserId")`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ALTER COLUMN "createdAt" SET DEFAULT '"2025-05-14T23:28:25.998Z"'`);
        await queryRunner.query(`ALTER TABLE "checklist" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."checklist_type"`);
        await queryRunner.query(`ALTER TABLE "checklist" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistFilled" DROP COLUMN "checklistId"`);
        await queryRunner.query(`ALTER TABLE "checklistFilled" ADD "checklistId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistQuestion" DROP COLUMN "checklistId"`);
        await queryRunner.query(`ALTER TABLE "checklistQuestion" ADD "checklistId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistQuestion" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."question_type"`);
        await queryRunner.query(`ALTER TABLE "checklistQuestion" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistQuestionItem" DROP COLUMN "checklistQuestionId"`);
        await queryRunner.query(`ALTER TABLE "checklistQuestionItem" ADD "checklistQuestionId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistQuestionOption" DROP COLUMN "checklistQuestionId"`);
        await queryRunner.query(`ALTER TABLE "checklistQuestionOption" ADD "checklistQuestionId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistFilledAnswer" DROP COLUMN "checklistFilledId"`);
        await queryRunner.query(`ALTER TABLE "checklistFilledAnswer" ADD "checklistFilledId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistFilledAnswer" DROP COLUMN "checklistQuestionId"`);
        await queryRunner.query(`ALTER TABLE "checklistFilledAnswer" ADD "checklistQuestionId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistFilledAnswer" ALTER COLUMN "checklistQuestion" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "UQ_c8639b7626fa94ba8265628f214"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "value" jsonb`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "createdAt" SET DEFAULT '"2025-05-14T23:28:26.024Z"'`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP CONSTRAINT "FK_ab130b920c820f5057feaa3a375"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP CONSTRAINT "FK_f4ccb304c20359898b80fee6d92"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP CONSTRAINT "FK_0ec0add611c71426f50dda0c957"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP COLUMN "dutyId"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD "dutyId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD CONSTRAINT "UQ_ab130b920c820f5057feaa3a375" UNIQUE ("dutyId")`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP COLUMN "vehicleId"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD "vehicleId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD CONSTRAINT "UQ_f4ccb304c20359898b80fee6d92" UNIQUE ("vehicleId")`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP COLUMN "checklistFilledId"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD "checklistFilledId" character varying`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP COLUMN "createdByUserId"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD "createdByUserId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD CONSTRAINT "UQ_0ec0add611c71426f50dda0c957" UNIQUE ("createdByUserId")`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD "createdAt" character varying NOT NULL DEFAULT '"2025-05-14T23:28:26.030Z"'`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP CONSTRAINT "FK_51d43c4975f9c092d3329206c0f"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP CONSTRAINT "FK_653ba767fc67a3b96e5d7f8d2d8"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP CONSTRAINT "FK_568fb13fa02c601ac9043ed3b77"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP COLUMN "dutyId"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD "dutyId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD CONSTRAINT "UQ_51d43c4975f9c092d3329206c0f" UNIQUE ("dutyId")`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP COLUMN "vehicleId"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD "vehicleId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD CONSTRAINT "UQ_653ba767fc67a3b96e5d7f8d2d8" UNIQUE ("vehicleId")`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP COLUMN "checklistFilledId"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD "checklistFilledId" character varying`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP COLUMN "createdByUserId"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD "createdByUserId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD CONSTRAINT "UQ_568fb13fa02c601ac9043ed3b77" UNIQUE ("createdByUserId")`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD "createdAt" character varying NOT NULL DEFAULT '"2025-05-14T23:28:26.036Z"'`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP CONSTRAINT "FK_8944d110ff146652e85a93f003d"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP CONSTRAINT "FK_8a8b39ae2337146554ed7191fbd"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP COLUMN "dutyId"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD "dutyId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD CONSTRAINT "UQ_8944d110ff146652e85a93f003d" UNIQUE ("dutyId")`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP COLUMN "checklistFilledId"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD "checklistFilledId" character varying`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP COLUMN "createdByUserId"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD "createdByUserId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD CONSTRAINT "UQ_8a8b39ae2337146554ed7191fbd" UNIQUE ("createdByUserId")`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD "createdAt" character varying NOT NULL DEFAULT '"2025-05-14T23:28:26.041Z"'`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_660cced3eb3232d317a712dd001" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD CONSTRAINT "FK_78aed4cb170c4e9c7ba680c46ba" FOREIGN KEY ("vehicleId") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD CONSTRAINT "FK_800582b77a039f930307845a062" FOREIGN KEY ("driverId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD CONSTRAINT "FK_8d237bd7fc350432caf1f1739bb" FOREIGN KEY ("createdByUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD CONSTRAINT "FK_1b9b613872a6965166623632721" FOREIGN KEY ("dutyId") REFERENCES "duty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD CONSTRAINT "FK_f967b4eafc0b1af447f956cabf0" FOREIGN KEY ("vehicleId") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD CONSTRAINT "FK_c7a2d2e78610ad29525679eaf1b" FOREIGN KEY ("createdByUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD CONSTRAINT "FK_ab130b920c820f5057feaa3a375" FOREIGN KEY ("dutyId") REFERENCES "duty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD CONSTRAINT "FK_f4ccb304c20359898b80fee6d92" FOREIGN KEY ("vehicleId") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD CONSTRAINT "FK_0ec0add611c71426f50dda0c957" FOREIGN KEY ("createdByUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD CONSTRAINT "FK_51d43c4975f9c092d3329206c0f" FOREIGN KEY ("dutyId") REFERENCES "duty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD CONSTRAINT "FK_653ba767fc67a3b96e5d7f8d2d8" FOREIGN KEY ("vehicleId") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD CONSTRAINT "FK_568fb13fa02c601ac9043ed3b77" FOREIGN KEY ("createdByUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD CONSTRAINT "FK_8944d110ff146652e85a93f003d" FOREIGN KEY ("dutyId") REFERENCES "duty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD CONSTRAINT "FK_8a8b39ae2337146554ed7191fbd" FOREIGN KEY ("createdByUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP CONSTRAINT "FK_8a8b39ae2337146554ed7191fbd"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP CONSTRAINT "FK_8944d110ff146652e85a93f003d"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP CONSTRAINT "FK_568fb13fa02c601ac9043ed3b77"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP CONSTRAINT "FK_653ba767fc67a3b96e5d7f8d2d8"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP CONSTRAINT "FK_51d43c4975f9c092d3329206c0f"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP CONSTRAINT "FK_0ec0add611c71426f50dda0c957"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP CONSTRAINT "FK_f4ccb304c20359898b80fee6d92"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP CONSTRAINT "FK_ab130b920c820f5057feaa3a375"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP CONSTRAINT "FK_c7a2d2e78610ad29525679eaf1b"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP CONSTRAINT "FK_f967b4eafc0b1af447f956cabf0"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP CONSTRAINT "FK_1b9b613872a6965166623632721"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP CONSTRAINT "FK_8d237bd7fc350432caf1f1739bb"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP CONSTRAINT "FK_800582b77a039f930307845a062"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP CONSTRAINT "FK_78aed4cb170c4e9c7ba680c46ba"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_660cced3eb3232d317a712dd001"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP CONSTRAINT "UQ_8a8b39ae2337146554ed7191fbd"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP COLUMN "createdByUserId"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD "createdByUserId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP COLUMN "checklistFilledId"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD "checklistFilledId" uuid`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP CONSTRAINT "UQ_8944d110ff146652e85a93f003d"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" DROP COLUMN "dutyId"`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD "dutyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD CONSTRAINT "FK_8a8b39ae2337146554ed7191fbd" FOREIGN KEY ("createdByUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD CONSTRAINT "FK_8944d110ff146652e85a93f003d" FOREIGN KEY ("dutyId") REFERENCES "duty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP CONSTRAINT "UQ_568fb13fa02c601ac9043ed3b77"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP COLUMN "createdByUserId"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD "createdByUserId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP COLUMN "checklistFilledId"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD "checklistFilledId" uuid`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP CONSTRAINT "UQ_653ba767fc67a3b96e5d7f8d2d8"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP COLUMN "vehicleId"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD "vehicleId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP CONSTRAINT "UQ_51d43c4975f9c092d3329206c0f"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" DROP COLUMN "dutyId"`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD "dutyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD CONSTRAINT "FK_568fb13fa02c601ac9043ed3b77" FOREIGN KEY ("createdByUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD CONSTRAINT "FK_653ba767fc67a3b96e5d7f8d2d8" FOREIGN KEY ("vehicleId") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD CONSTRAINT "FK_51d43c4975f9c092d3329206c0f" FOREIGN KEY ("dutyId") REFERENCES "duty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP CONSTRAINT "UQ_0ec0add611c71426f50dda0c957"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP COLUMN "createdByUserId"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD "createdByUserId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP COLUMN "checklistFilledId"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD "checklistFilledId" uuid`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP CONSTRAINT "UQ_f4ccb304c20359898b80fee6d92"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP COLUMN "vehicleId"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD "vehicleId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP CONSTRAINT "UQ_ab130b920c820f5057feaa3a375"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" DROP COLUMN "dutyId"`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD "dutyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD CONSTRAINT "FK_0ec0add611c71426f50dda0c957" FOREIGN KEY ("createdByUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD CONSTRAINT "FK_f4ccb304c20359898b80fee6d92" FOREIGN KEY ("vehicleId") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD CONSTRAINT "FK_ab130b920c820f5057feaa3a375" FOREIGN KEY ("dutyId") REFERENCES "duty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "value" json`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "UQ_c8639b7626fa94ba8265628f214" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "checklistFilledAnswer" ALTER COLUMN "checklistQuestion" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistFilledAnswer" DROP COLUMN "checklistQuestionId"`);
        await queryRunner.query(`ALTER TABLE "checklistFilledAnswer" ADD "checklistQuestionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistFilledAnswer" DROP COLUMN "checklistFilledId"`);
        await queryRunner.query(`ALTER TABLE "checklistFilledAnswer" ADD "checklistFilledId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistQuestionOption" DROP COLUMN "checklistQuestionId"`);
        await queryRunner.query(`ALTER TABLE "checklistQuestionOption" ADD "checklistQuestionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistQuestionItem" DROP COLUMN "checklistQuestionId"`);
        await queryRunner.query(`ALTER TABLE "checklistQuestionItem" ADD "checklistQuestionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistQuestion" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."question_type" AS ENUM('TEXT', 'OPTION', 'SELECT')`);
        await queryRunner.query(`ALTER TABLE "checklistQuestion" ADD "type" "public"."question_type" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistQuestion" DROP COLUMN "checklistId"`);
        await queryRunner.query(`ALTER TABLE "checklistQuestion" ADD "checklistId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklistFilled" DROP COLUMN "checklistId"`);
        await queryRunner.query(`ALTER TABLE "checklistFilled" ADD "checklistId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklist" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."checklist_type" AS ENUM('DUTY_CARE', 'DRIVER', 'RESCUER', 'RADIO_OPERATOR')`);
        await queryRunner.query(`ALTER TABLE "checklist" ADD "type" "public"."checklist_type" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP CONSTRAINT "UQ_c7a2d2e78610ad29525679eaf1b"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "createdByUserId"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "createdByUserId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "checklistFilledId"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "checklistFilledId" uuid`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "incidentContinuation"`);
        await queryRunner.query(`CREATE TYPE "public"."incident_continuation" AS ENUM('REMOVAL', 'REFUSED')`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "incidentContinuation" "public"."incident_continuation" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "victimGender"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "victimGender" character NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP CONSTRAINT "UQ_f967b4eafc0b1af447f956cabf0"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "vehicleId"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "vehicleId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "time"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "time" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP CONSTRAINT "UQ_1b9b613872a6965166623632721"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" DROP COLUMN "dutyId"`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD "dutyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD CONSTRAINT "FK_c7a2d2e78610ad29525679eaf1b" FOREIGN KEY ("createdByUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD CONSTRAINT "FK_f967b4eafc0b1af447f956cabf0" FOREIGN KEY ("vehicleId") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP CONSTRAINT "UQ_8d237bd7fc350432caf1f1739bb"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP COLUMN "createdByUserId"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD "createdByUserId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP COLUMN "endAt"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD "endAt" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP COLUMN "startAt"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD "startAt" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP CONSTRAINT "UQ_800582b77a039f930307845a062"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP COLUMN "driverId"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD "driverId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP CONSTRAINT "UQ_78aed4cb170c4e9c7ba680c46ba"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" DROP COLUMN "vehicleId"`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD "vehicleId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD CONSTRAINT "FK_8d237bd7fc350432caf1f1739bb" FOREIGN KEY ("createdByUserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD CONSTRAINT "FK_800582b77a039f930307845a062" FOREIGN KEY ("driverId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicleTrip" ADD CONSTRAINT "FK_78aed4cb170c4e9c7ba680c46ba" FOREIGN KEY ("vehicleId") REFERENCES "vehicle"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vehicle" ALTER COLUMN "isAvailable" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "createdAt" date NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "duty" ALTER COLUMN "note" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "duty" ALTER COLUMN "note" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "isAvailable"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "isAvailable" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "traineeId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "traineeId" uuid`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "assistantRadioOperatorId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "assistantRadioOperatorId" uuid`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "radioOperatorId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "radioOperatorId" uuid`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "secondRescuerId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "secondRescuerId" uuid`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "firstRescuerId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "firstRescuerId" uuid`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "driverId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "driverId" uuid`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "leaderId"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "leaderId" uuid`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "shift"`);
        await queryRunner.query(`CREATE TYPE "public"."duty_shift" AS ENUM('DAY', 'NIGHT')`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "shift" "public"."duty_shift" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "duty" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "duty" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequestPosition" DROP COLUMN "position"`);
        await queryRunner.query(`CREATE TYPE "public"."dutyRequestPosition_position_enum" AS ENUM('DRIVER', 'LEADER', 'RESCUER', 'RADIO_OPERATOR', 'ASSISTANT_RADIO_OPERATOR', 'TRAINEE')`);
        await queryRunner.query(`ALTER TABLE "dutyRequestPosition" ADD "position" "public"."dutyRequestPosition_position_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequestPosition" DROP COLUMN "dutyRequestId"`);
        await queryRunner.query(`ALTER TABLE "dutyRequestPosition" ADD "dutyRequestId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "createdAt" date NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "deletedAt" date`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "endAt"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "endAt" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "startAt"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "startAt" TIME NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "shift"`);
        await queryRunner.query(`CREATE TYPE "public"."duty_shift" AS ENUM('DAY', 'NIGHT')`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "shift" "public"."duty_shift" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" DROP COLUMN "date"`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD "date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "approvedBy"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "approvedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_660cced3eb3232d317a712dd001"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "courseId"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "courseId" uuid`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "deletedBy"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "deletedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."user_status" AS ENUM('ACTIVE', 'DELETED', 'PENDING', 'SUSPENDED')`);
        await queryRunner.query(`ALTER TABLE "user" ADD "status" "public"."user_status" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "permission"`);
        await queryRunner.query(`CREATE TYPE "public"."user_permission" AS ENUM('TRAINEE', 'ASSISTANT_RADIO_OPERATOR', 'ADMIN', 'VOLUNTARY')`);
        await queryRunner.query(`ALTER TABLE "user" ADD "permission" "public"."user_permission" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22"`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "radioOperatorChecklist" ADD CONSTRAINT "FK_00927e963a8a4c3b0f9f06c1aa0" FOREIGN KEY ("checklistFilledId") REFERENCES "checklistFilled"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rescuerChecklist" ADD CONSTRAINT "FK_04dc7ec62b5c70614ca5055d316" FOREIGN KEY ("checklistFilledId") REFERENCES "checklistFilled"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driverChecklist" ADD CONSTRAINT "FK_49d69c43dcc611ab038cabcb132" FOREIGN KEY ("checklistFilledId") REFERENCES "checklistFilled"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklistFilledAnswer" ADD CONSTRAINT "FK_3b88b91acc96fa110dbca8bdf3b" FOREIGN KEY ("checklistFilledId") REFERENCES "checklistFilled"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklistQuestionOption" ADD CONSTRAINT "FK_b5773438b5a3723dcbcc3f7fea7" FOREIGN KEY ("checklistQuestionId") REFERENCES "checklistQuestion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklistQuestionItem" ADD CONSTRAINT "FK_0bdcd18d14d0dbe1b546e0688c6" FOREIGN KEY ("checklistQuestionId") REFERENCES "checklistQuestion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklistQuestion" ADD CONSTRAINT "FK_2cf93290d25cc20f5e1ca3fe248" FOREIGN KEY ("checklistId") REFERENCES "checklist"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklistFilled" ADD CONSTRAINT "FK_12e865c85e6303467ce0962e0a4" FOREIGN KEY ("checklistId") REFERENCES "checklist"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dutyCareChecklist" ADD CONSTRAINT "FK_713225778ff4cffe1f55d535b7d" FOREIGN KEY ("checklistFilledId") REFERENCES "checklistFilled"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "duty" ADD CONSTRAINT "FK_6a066490fc535fc3aaf3118a29a" FOREIGN KEY ("traineeId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "duty" ADD CONSTRAINT "FK_9066788443fa413b6b247125249" FOREIGN KEY ("assistantRadioOperatorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "duty" ADD CONSTRAINT "FK_0b047dd0eba2c67fa5bc88c6a1e" FOREIGN KEY ("radioOperatorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "duty" ADD CONSTRAINT "FK_f5b4ceb89f9a290d99b6f1a4a3d" FOREIGN KEY ("secondRescuerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "duty" ADD CONSTRAINT "FK_19582ae87fdb3eab7a97680122f" FOREIGN KEY ("firstRescuerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "duty" ADD CONSTRAINT "FK_f868506683edeb8fa7d4fb00482" FOREIGN KEY ("driverId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "duty" ADD CONSTRAINT "FK_81904955122e0a5759c6f9d79ab" FOREIGN KEY ("leaderId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dutyRequestPosition" ADD CONSTRAINT "FK_143a4eba4f39ad407626f68d71a" FOREIGN KEY ("dutyRequestId") REFERENCES "dutyRequest"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dutyRequest" ADD CONSTRAINT "FK_4133c0b3d932b97c4edd337f073" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "fk_user_course" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
